version: "3.3"
services:
  api:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./api/:/var/www/html/"
    ports:
      - "8000:80"
  front:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./front/:/var/www/html/"
    ports:
      - "8080:80"
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
volumes:
  mysql-data:
