<header class="row">
    <h2 class="col-10">Product Table</h2>
    <a href="/index/logout" class="btn btn-warning col-2">LogOut</a>
</header>
<main>
    <table class="table table-striped table-hover my-4">
        <caption>Product Table</caption>
        <thead>
            <tr>
                <th>Product ID</th>
                <th>Product Name</th>
            </tr>
        </thead>
        <tbody>
            <?php
            echo $txt;
            ?>
        </tbody>
    </table>
</main>
